### PR TITLE
Handle `occursin_msg(s, nothing)` fallback

### LINKED ISSUE #130: `@test_log` errors when `msg` doesn't match
This should be a test failure, but instead it is an error (on Memento `v0.12.1`)

#### Example:
```julia
julia> using Memento

julia> using Memento.TestUtils

julia> @testset "oops" begin
           @test_log getlogger() "info" r".*foo.*" info(getlogger(), "foobar")
       end
Test Summary: | Pass  Total
oops          |    2      2
Test.DefaultTestSet("oops", Any[], 2, false)

julia> @testset "oops" begin
           @test_log getlogger() "info" r".*foo.*" info(getlogger(), "baz")
       end
oops: Test Failed at /Users/nick/.julia/packages/Memento/UgJr2/src/memento_test.jl:36
  Expression: handler.found[1] == $(Expr(:escape, "info"))
   Evaluated: nothing == "info"
Stacktrace:
 [1] (::getfield(Main, Symbol("##51#52")){Memento.TestUtils.TestHandler{DefaultFormatter,Base.GenericIOBuffer{Array{UInt8,1}}}})() at /Users/nick/.julia/packages/Memento/UgJr2/src/memento_test.jl:36
 [2] setpropagating!(::getfield(Main, Symbol("##51#52")){Memento.TestUtils.TestHandler{DefaultFormatter,Base.GenericIOBuffer{Array{UInt8,1}}}}, ::Logger, ::Bool) at /Users/nick/.julia/packages/Memento/UgJr2/src/loggers.jl:113
 [3] top-level scope at /Users/nick/.julia/packages/Memento/UgJr2/src/memento_test.jl:34
 [4] top-level scope at REPL[194]:2
 [5] top-level scope at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1113
 [6] top-level scope at REPL[194]:2
oops: Error During Test at /Users/nick/.julia/packages/Memento/UgJr2/src/memento_test.jl:37
  Test threw exception
  Expression: occursin_msg($(Expr(:escape, :(#= REPL[194]:2 =# @r_str ".*foo.*"))), handler.found[2])
  MethodError: no method matching occursin(::Regex, ::Nothing)
  Closest candidates are:
    occursin(::Regex, !Matched::SubString; offset) at regex.jl:172
    occursin(::Regex, !Matched::AbstractString; offset) at regex.jl:166
  Stacktrace:
   [1] occursin_msg(::Regex, ::Nothing) at /Users/nick/.julia/packages/Memento/UgJr2/src/memento_test.jl:15
   [2] (::getfield(Main, Symbol("##51#52")){Memento.TestUtils.TestHandler{DefaultFormatter,Base.GenericIOBuffer{Array{UInt8,1}}}})() at /Users/nick/.julia/packages/Memento/UgJr2/src/memento_test.jl:37
   [3] setpropagating!(::getfield(Main, Symbol("##51#52")){Memento.TestUtils.TestHandler{DefaultFormatter,Base.GenericIOBuffer{Array{UInt8,1}}}}, ::Logger, ::Bool) at /Users/nick/.julia/packages/Memento/UgJr2/src/loggers.jl:113
   [4] top-level scope at /Users/nick/.julia/packages/Memento/UgJr2/src/memento_test.jl:34
   [5] top-level scope at REPL[194]:2
   [6] top-level scope at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1113
   [7] top-level scope at REPL[194]:2

Test Summary: | Fail  Error  Total
oops          |    1      1      2
ERROR: Some tests did not pass: 0 passed, 1 failed, 1 errored, 0 broken.
```

#### Possible fix
add a method for the `nothing` case to `occursin_msg`, e.g. 
```julia
occursin_msg(s, ::Nothing) = false
```
at
https://github.com/invenia/Memento.jl/blob/d537259efc95ad51af79d6f38e03fc96b25fc1f9/src/memento_test.jl#L14

### PR DESCRIPTION
**Pull request by rofinn**
Only test occursin_msg after checking if the level was found. and `nothing` case. Closes #130

### CODE REVIEW

File: src/memento_test.jl [hunk 1]
```diff
@@ -15,6 +15,7 @@ occursin_msg(s::AbstractString, output) = occursin(s, output)
 occursin_msg(s::Regex, output) = occursin(s, output)
 occursin_msg(s::Function, output) = s(output)
 occursin_msg(S::Union{AbstractArray,Tuple}, output) = all(s -> occursin_msg(s, output), S)
+occursin_msg(s, ::Nothing) = false  # Fallback, but shouldn't be needed
```
Comment (oxinabox) [inline src/memento_test.jl]: This comment confuses me

Comment (rofinn) [reply src/memento_test.jl]: It's cause our test logger is always setting both the found level and message only when we actually find something, so if `handler.found[1] == $(esc(level))` returns true then `occursin_msg($(esc(msg)), handler.found[2])` will not hit this dispatch. The reason we were hitting this before is because is because we had separate `@test` calls for those two conditions, now we just have 1 short-circuited test.

Comment (oxinabox) [reply src/memento_test.jl]: So this is dead code.
Lets not have it then?

Comment (rofinn) [reply src/memento_test.jl]: 👌

File: test/test.jl [hunk 2]
```diff
@@ -24,6 +24,7 @@
         @test_nolog(logger, "info", msg, Memento.debug(logger, msg))
         @test_nolog(logger, "info", msg, Memento.info(logger, different_msg))
         @test_nolog(logger, "info", msg, Memento.warn(logger, different_msg))
+        @test_nolog(logger, "info", r".*foo.*", info(logger, "baz"))
```
Comment (oxinabox) [inline test/test.jl]:
```suggestion
        @test_nolog(logger, "info", r".*foo.*", Memento.info(logger, "baz"))
```

Fixes tests in 0.7

Should drop 0.7 but that is another PR
