### PR TITLE
Avoid overwriting registered loggers at runtime

### LINKED ISSUE #107: Catching @test_warn Errors
This example was tested with the following packages on Julia v0.7,
- PowerModels v0.8.8
- Memento v0.10.0
- TestPkg v0.0.0 #master git@github.com:ccoffrin/TestPkg.git

The following code works as expected,
```
module ModB
    using PowerModels
    using Memento

    const PMs = PowerModels

    const LOGGER = getlogger(PowerModels)

    function danger()
        warn(LOGGER, "ModB warning")
    end

    function danger(expr::AbstractString)
        warn(LOGGER, "ModB warning \"$expr\"")
    end
end

using Test; using PowerModels; using Memento
TESTLOG = getlogger(PowerModels)

ModB.danger()

@test_warn(TESTLOG, "", ModB.danger())
@test_warn(TESTLOG, "ModB warning", ModB.danger())
```
Has the output,
```
julia> ModB.danger()
[warn | PowerModels]: ModB warning

julia> @test_warn(TESTLOG, "", ModB.danger())

julia> @test_warn(TESTLOG, "ModB warning", ModB.danger())
```

However, if I take the same code and put it in a package (see, [TestPkg.jl](https://github.com/ccoffrin/TestPkg)) then the warnings stop being captured by `@test_warn`.  For example,
```
using TestPkg

using Memento; using PowerModels; using Test
TESTLOG = getlogger(PowerModels)

TestPkg.danger()

@test_warn(TESTLOG, "", TestPkg.danger())
@test_warn(TESTLOG, "TestPkg warning", TestPkg.danger())
```
results in the following,
```
julia> TestPkg.danger()
[warn | PowerModels]: TestPkg warning

julia> @test_warn(TESTLOG, "", TestPkg.danger())
[warn | PowerModels]: TestPkg warning
Test Failed at /Users/carleton/.julia/packages/Memento/QMKyB/src/memento_test.jl:35
  Expression: handler.found[1] == $(Expr(:escape, "warn"))
   Evaluated: "" == "warn"
ERROR: There was an error during testing

julia> @test_warn(TESTLOG, "TestPkg warning", TestPkg.danger())
[warn | PowerModels]: TestPkg warning
Test Failed at /Users/carleton/.julia/packages/Memento/QMKyB/src/memento_test.jl:35
  Expression: handler.found[1] == $(Expr(:escape, "warn"))
   Evaluated: "" == "warn"
ERROR: There was an error during testing
```

### PR DESCRIPTION
**Pull request by nicoleepp**
Closes #107

### CODE REVIEW

File: src/loggers.jl [hunk 1]
```diff
@@ -133,9 +133,13 @@ getlevels(logger::Logger) = logger.levels
...
     register(::Logger)
 
-Register an existing logger with Memento.
+Register an existing logger with Memento if it has not already been registered.
 """
-register(logger::Logger) = _loggers[logger.name] = logger
+function register(logger::Logger)
+    if !in(logger.name, keys(_loggers))
+        _loggers[logger.name] = logger
+    end
```
Comment (rofinn) [inline src/loggers.jl]: Maybe we should log a debug message if a logger is already registered? Memento should probably register a logger of its own to help with debugging in the future.

File: src/loggers.jl [hunk 2]
```diff
@@ -133,9 +133,13 @@ getlevels(logger::Logger) = logger.levels
 """
     register(::Logger)
 
-Register an existing logger with Memento.
+Register an existing logger with Memento if it has not already been registered.
 """
-register(logger::Logger) = _loggers[logger.name] = logger
+function register(logger::Logger)
+    if !in(logger.name, keys(_loggers))
```
Comment (ararslan) [inline src/loggers.jl]:
```suggestion
    if !haskey(_loggers, logger.name)
```
