### PR TITLE
Change sentinel for test_warn error message

### LINKED ISSUE #106: Error Message for @test_warn
Testing the following code on Julia v0.7 and Memento v0.10,
```
module ModA
    using Memento

    const LOGGER = getlogger(@__MODULE__)
    __init__() = Memento.register(LOGGER)

    function danger()
        warn(LOGGER, "ModA warning")
    end
end

ModA.danger()

using Memento
using Compat.Test
TESTLOG = getlogger(Main.ModA)

@test_warn(TESTLOG, "ModA warning", ModA.danger())

@test_warn(TESTLOG, "ModA warning 1", ModA.danger())
```
The last line results in,
```
Test Failed at /Users/carleton/.julia/packages/Memento/QMKyB/src/memento_test.jl:35
  Expression: handler.found[1] == $(Expr(:escape, "warn"))
   Evaluated: "" == "warn"
ERROR: There was an error during testing
```
Is this the intended error message?  Seems a bit cryptic to me.

### PR DESCRIPTION
**Pull request by nicoleepp**
Closes #106 

The error message printed would be:

```julia
julia> @test_warn(TESTLOG, "ModA warning 1", ModA.danger())
Test Failed at /Users/nicoleepp/.julia/dev/Memento/src/memento_test.jl:34
  Expression: handler.found[1] == $(Expr(:escape, "warn"))
   Evaluated: nothing == "warn"
ERROR: There was an error during testing
```

Which to me is clearer than "" since the pattern matching didn't find anything. Open to better sentinel suggestions though.

### CODE REVIEW

File: src/memento_test.jl [hunk 1]
```diff
@@ -75,7 +75,7 @@ end
 
 function TestHandler(level, msg)
     TestHandler{DefaultFormatter, IOBuffer}(
-        String(level), msg, ("", "")
+        String(level), msg, (nothing, "")
```
Comment (nicoleepp) [inline src/memento_test.jl]: Actually both of the `""` should probably be `nothing`
